-- MySQL Script generated by MySQL Workbench
-- Wed May 19 15:56:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema skc_cup
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Applicant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Applicant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Applicant` (
  `ApplicantID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleNames` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `MaritalStatus` ENUM('Never married', 'Widowed', 'Divorced', 'Separated', 'Married') NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `ZIPCode` VARCHAR(10) NULL,
  `Street` VARCHAR(45) NOT NULL,
  `HouseNumber` VARCHAR(10) NOT NULL,
  `DOB` DATE NOT NULL,
  PRIMARY KEY (`ApplicantID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RejectionReason`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RejectionReason` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RejectionReason` (
  `RejectionReasonNumber` INT NOT NULL AUTO_INCREMENT,
  `Reason` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`RejectionReasonNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `MemberNumber` INT NOT NULL,
  `Title` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `Middle Names` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `ZIP Code` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NOT NULL,
  `HouseNumber` VARCHAR(10) NOT NULL,
  `DateOfDeath` DATE NULL,
  `CurrentMemberCategory` ENUM('fellowship', 'honoured fellowship') NOT NULL,
  `CurrentMemberType` ENUM('Provisional', 'Restricted', 'Full', 'Esteemed Royal Fellow', 'Overseas Fellow', '50 Year Fellow', 'Life Fellow') NOT NULL,
  `JoinDate` DATE NOT NULL,
  `MobilePhone` VARCHAR(16) NULL,
  `HomePhone` VARCHAR(16) NULL,
  `WorkPhone` VARCHAR(16) NULL,
  PRIMARY KEY (`MemberNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Application` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Application` (
  `WhenApplied` DATE NOT NULL,
  `ApplicantID` INT NOT NULL,
  `Verdict` ENUM('approved', 'rejected') NOT NULL,
  `WhenApproved` DATETIME NULL,
  `DateRejected` DATE NULL,
  `RejectionReasonNumber` INT NULL,
  `RefereeOneMemberNumber` INT NOT NULL,
  `RefereeTwoMemberNumber` INT NOT NULL,
  `ReferenceOne` TEXT NOT NULL,
  `ReferenceTwo` TEXT NOT NULL,
  `StatementOfAchievement` TEXT NOT NULL,
  PRIMARY KEY (`WhenApplied`, `ApplicantID`),
  INDEX `fk_Application_RejectionReason1_idx` (`RejectionReasonNumber` ASC) VISIBLE,
  INDEX `fk_Application_Applicant1_idx` (`ApplicantID` ASC) VISIBLE,
  INDEX `fk_Application_Member1_idx` (`RefereeOneMemberNumber` ASC) VISIBLE,
  INDEX `fk_Application_Member2_idx` (`RefereeTwoMemberNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Application_RejectionReason1`
    FOREIGN KEY (`RejectionReasonNumber`)
    REFERENCES `mydb`.`RejectionReason` (`RejectionReasonNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_Applicant1`
    FOREIGN KEY (`ApplicantID`)
    REFERENCES `mydb`.`Applicant` (`ApplicantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_Member1`
    FOREIGN KEY (`RefereeOneMemberNumber`)
    REFERENCES `mydb`.`Member` (`MemberNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_Member2`
    FOREIGN KEY (`RefereeTwoMemberNumber`)
    REFERENCES `mydb`.`Member` (`MemberNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EventType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventType` (
  `PublicOrPrivate` ENUM('public', 'private') NOT NULL,
  `EventTypeName` VARCHAR(45) NOT NULL,
  `PercentageOfBasicFee` DECIMAL(4,1) NOT NULL,
  PRIMARY KEY (`PublicOrPrivate`, `EventTypeName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venue` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venue` (
  `RoomName` VARCHAR(45) NOT NULL,
  `Configuration` VARCHAR(45) NOT NULL,
  `ConfigurationCapacity` INT NOT NULL,
  `RoomFloor` VARCHAR(20) NOT NULL,
  `RoomWidth` INT NOT NULL,
  `RoomLength` INT NOT NULL,
  `BasicFee` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`RoomName`, `Configuration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `EventID` INT NOT NULL AUTO_INCREMENT,
  `IsVirtual` TINYINT(1) NOT NULL,
  `Status` ENUM('pending approvial', 'upcoming', 'happening now', 'postponed', 'cancelled') NOT NULL,
  `RegistrationLink` VARCHAR(120) NOT NULL,
  `WebinarLink` VARCHAR(120) NULL,
  `BookingAccepted` TINYINT(1) NOT NULL,
  `ScheduledStart` DATETIME NOT NULL,
  `CapacityLimit` INT NOT NULL,
  `PublicOrPrivate` ENUM('public', 'private') NOT NULL,
  `EventTypeName` VARCHAR(45) NOT NULL,
  `RoomName` VARCHAR(45) NOT NULL,
  `Configuration` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EventID`),
  INDEX `fk_Event_EventType1_idx` (`PublicOrPrivate` ASC, `EventTypeName` ASC) VISIBLE,
  INDEX `fk_Event_Venue1_idx` (`RoomName` ASC, `Configuration` ASC) VISIBLE,
  CONSTRAINT `fk_Event_EventType1`
    FOREIGN KEY (`PublicOrPrivate` , `EventTypeName`)
    REFERENCES `mydb`.`EventType` (`PublicOrPrivate` , `EventTypeName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Venue1`
    FOREIGN KEY (`RoomName` , `Configuration`)
    REFERENCES `mydb`.`Venue` (`RoomName` , `Configuration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `RoleNumber` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member_Organises_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Member_Organises_Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Member_Organises_Event` (
  `EventID` INT NOT NULL,
  `MemberNumber` INT NOT NULL,
  `RoleNumber` INT NOT NULL,
  INDEX `fk_RoleInOrganising_Event1_idx` (`EventID` ASC) VISIBLE,
  INDEX `fk_RoleInOrganising_Member1_idx` (`MemberNumber` ASC) VISIBLE,
  PRIMARY KEY (`EventID`, `MemberNumber`, `RoleNumber`),
  INDEX `fk_Member_Organises_Event_Role1_idx` (`RoleNumber` ASC) VISIBLE,
  CONSTRAINT `fk_RoleInOrganising_Event1`
    FOREIGN KEY (`EventID`)
    REFERENCES `mydb`.`Event` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoleInOrganising_Member1`
    FOREIGN KEY (`MemberNumber`)
    REFERENCES `mydb`.`Member` (`MemberNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_Organises_Event_Role1`
    FOREIGN KEY (`RoleNumber`)
    REFERENCES `mydb`.`Role` (`RoleNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recording`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recording` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recording` (
  `RecordingLink` VARCHAR(120) NOT NULL,
  `EventID` INT NOT NULL,
  PRIMARY KEY (`RecordingLink`, `EventID`),
  INDEX `fk_Recording_Event1_idx` (`EventID` ASC) VISIBLE,
  CONSTRAINT `fk_Recording_Event1`
    FOREIGN KEY (`EventID`)
    REFERENCES `mydb`.`Event` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MemberTypeInterval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MemberTypeInterval` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MemberTypeInterval` (
  `MemberNumber` INT NOT NULL,
  `MemberType` ENUM('Provisional', 'Restricted', 'Full', 'Esteemed Royal Fellow', 'Overseas Fellow', '50 Year Fellow', 'Life Fellow') NOT NULL,
  `DateAwarded` DATE NOT NULL,
  `DateEnded` DATE NOT NULL,
  PRIMARY KEY (`MemberNumber`, `MemberType`, `DateAwarded`),
  INDEX `fk_MemberTypeInterval_Member1_idx` (`MemberNumber` ASC) VISIBLE,
  CONSTRAINT `fk_MemberTypeInterval_Member1`
    FOREIGN KEY (`MemberNumber`)
    REFERENCES `mydb`.`Member` (`MemberNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`club` (
  `ClubId` INT NOT NULL,
  `ClubName` VARCHAR(45) NOT NULL,
  `CoachFirstName` VARCHAR(45) NOT NULL,
  `CoachSurname` VARCHAR(45) NOT NULL,
  `Premierships` INT NULL,
  `Abbreviation` VARCHAR(3) NULL,
  PRIMARY KEY (`ClubId`),
  UNIQUE INDEX `ClubId_UNIQUE` (`ClubId` ASC) VISIBLE,
  UNIQUE INDEX `ClubName_UNIQUE` (`ClubName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`season` ;

CREATE TABLE IF NOT EXISTS `mydb`.`season` (
  `Year` YEAR NOT NULL,
  `Code` VARCHAR(30) NULL,
  `IsFinals` TINYINT(1) NULL,
  `Subscription` VARCHAR(45) NULL,
  `Size` INT NULL,
  `IsPublic` TINYINT(1) NULL,
  `Name` VARCHAR(45) NULL,
  `FinalsLength` INT NULL,
  `FinalsSize` INT NOT NULL,
  `FinalsStartRound` INT NULL,
  `EndRound` INT NULL,
  `LeagueRank` INT NULL,
  `StartRound` INT NULL,
  `SquadFormation` VARCHAR(45) NOT NULL,
  `IsKeeper` TINYINT(1) NULL,
  `IsPlayingByes` TINYINT(1) NULL,
  `PointsLast` INT NULL,
  `WaiverPeriod` INT NULL,
  `TradeWaivers` INT NULL,
  `WaiverOrder` INT NULL,
  `RfaPrivacy` VARCHAR(45) NULL,
  `ApproveTrade` VARCHAR(45) NULL,
  `IsDppAdditions` TINYINT(1) NULL,
  `TogThreshold` INT NULL,
  `IsCaptains` TINYINT(1) NULL,
  `EmergencyLimit` INT NULL,
  `Lockout` INT NULL,
  `IsCustomScoring` TINYINT(1) NULL,
  `RegeneratedFrom` INT NULL,
  `NumMatchups` VARCHAR(45) NULL,
  `PointAverage` FLOAT NULL,
  `TotalPoints` INT NULL,
  `IsCoachesBox` TINYINT(1) NULL,
  `IsEmergencies` TINYINT(1) NULL,
  `RankBy` VARCHAR(45) NULL,
  `PlateFinalsLength` INT NULL,
  PRIMARY KEY (`Year`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`round` ;

CREATE TABLE IF NOT EXISTS `mydb`.`round` (
  `Number` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `IsPractice` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Number`, `Year`),
  INDEX `fk_round_season1_idx` (`Year` ASC) VISIBLE,
  CONSTRAINT `fk_round_season1`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`season` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ladder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ladder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ladder` (
  `PremiershipPoints` INT NOT NULL,
  `LadderRank` INT NOT NULL,
  `ClubId` INT NOT NULL,
  `RoundNumber` INT NOT NULL,
  `Year` YEAR NOT NULL,
  INDEX `fk_club_on_ladder_club1_idx` (`ClubId` ASC) VISIBLE,
  PRIMARY KEY (`ClubId`, `RoundNumber`, `Year`),
  INDEX `fk_club_on_ladder_round1_idx` (`RoundNumber` ASC, `Year` ASC) VISIBLE,
  CONSTRAINT `fk_club_on_ladder_club1`
    FOREIGN KEY (`ClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_club_on_ladder_round1`
    FOREIGN KEY (`RoundNumber` , `Year`)
    REFERENCES `mydb`.`round` (`Number` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`campaign` ;

CREATE TABLE IF NOT EXISTS `mydb`.`campaign` (
  `ClubId` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `IsCommissioner` TINYINT(1) NOT NULL,
  `IsPlateWinner` TINYINT(1) NULL,
  `IsFixtureWinner` TINYINT(1) NULL,
  PRIMARY KEY (`ClubId`, `Year`),
  INDEX `fk_club plays season_season1_idx` (`Year` ASC) VISIBLE,
  CONSTRAINT `fk_club plays season_club1`
    FOREIGN KEY (`ClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_club plays season_season1`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`season` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`draft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`draft` ;

CREATE TABLE IF NOT EXISTS `mydb`.`draft` (
  `StartDate` DATETIME NOT NULL,
  `Type` ENUM('live') NULL,
  `HowOrdered` ENUM('snake') NULL,
  `Year` YEAR NOT NULL,
  PRIMARY KEY (`StartDate`),
  INDEX `fk_draft_season1_idx` (`Year` ASC) VISIBLE,
  CONSTRAINT `fk_draft_season1`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`season` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `PlayerId` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PlayerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pick`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pick` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pick` (
  `Number` INT NOT NULL,
  `DraftStartDate` DATETIME NOT NULL,
  `ClubId` INT NOT NULL,
  `PlayerId` INT NOT NULL,
  PRIMARY KEY (`Number`, `DraftStartDate`),
  INDEX `fk_pick_draft1_idx` (`DraftStartDate` ASC) VISIBLE,
  INDEX `fk_pick_club1_idx` (`ClubId` ASC) VISIBLE,
  INDEX `fk_pick_player1_idx` (`PlayerId` ASC) VISIBLE,
  CONSTRAINT `fk_pick_draft1`
    FOREIGN KEY (`DraftStartDate`)
    REFERENCES `mydb`.`draft` (`StartDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pick_club1`
    FOREIGN KEY (`ClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pick_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player_season` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player_season` (
  `Adp` INT NULL,
  `Ranked` INT NULL,
  `AflTeam` ENUM('ADE', 'BRI', 'CAR', 'COL', 'ESS', 'FRE', 'GEE', 'GCS', 'GWS', 'HAW', 'MEL', 'NTH', 'PTA', 'RIC', 'STK', 'SYD', 'WCE', 'WBD') NOT NULL,
  `OriginalPositionOne` ENUM('DEF', 'MID', 'RUC', 'FWD') NOT NULL,
  `OriginalPositionTwo` ENUM('DEF', 'MID', 'RUC', 'FWD') NULL,
  `PlayerId` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `AvgTog` FLOAT NULL,
  PRIMARY KEY (`PlayerId`, `Year`),
  INDEX `fk_player season_season1_idx` (`Year` ASC) VISIBLE,
  CONSTRAINT `fk_player season_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player season_season1`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`season` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fixture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fixture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fixture` (
  `HomeClubId` INT NOT NULL,
  `AwayClubId` INT NULL,
  `RoundNumber` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `HomeScore` INT NULL,
  `AwayScore` INT NULL,
  PRIMARY KEY (`HomeClubId`, `RoundNumber`, `Year`),
  INDEX `fk_weekly squad_round1_idx` (`RoundNumber` ASC, `Year` ASC) VISIBLE,
  INDEX `fk_weekly_squad_club1_idx` (`AwayClubId` ASC) VISIBLE,
  CONSTRAINT `fk_weekly squad_club1`
    FOREIGN KEY (`HomeClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weekly squad_round1`
    FOREIGN KEY (`RoundNumber` , `Year`)
    REFERENCES `mydb`.`round` (`Number` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weekly_squad_club1`
    FOREIGN KEY (`AwayClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_selection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player_selection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player_selection` (
  `Position` ENUM('DEF', 'MID', 'RUC', 'FWD', 'bench', 'DEF emergency', 'MID emergency', 'RUC emergency', 'FWD emergency') NOT NULL,
  `PlayerId` INT NOT NULL,
  `RoundNumber` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `ClubId` INT NOT NULL,
  PRIMARY KEY (`PlayerId`, `Year`, `RoundNumber`),
  INDEX `fk_player selection_player1_idx` (`PlayerId` ASC) VISIBLE,
  INDEX `fk_player_selection_fixture1_idx` (`RoundNumber` ASC, `Year` ASC) VISIBLE,
  INDEX `fk_player_selection_club1_idx` (`ClubId` ASC) VISIBLE,
  CONSTRAINT `fk_player selection_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_selection_fixture1`
    FOREIGN KEY (`RoundNumber` , `Year`)
    REFERENCES `mydb`.`fixture` (`RoundNumber` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_selection_club1`
    FOREIGN KEY (`ClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trade` (
  `TradeId` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `ClubOneId` INT NOT NULL,
  `ClubTwoId` INT NOT NULL,
  `BeforeRound` INT NOT NULL,
  `Year` YEAR NOT NULL,
  PRIMARY KEY (`TradeId`, `Year`),
  INDEX `fk_transaction_club1_idx` (`ClubOneId` ASC) VISIBLE,
  INDEX `fk_transaction_club2_idx` (`ClubTwoId` ASC) VISIBLE,
  INDEX `fk_transaction_round1_idx` (`BeforeRound` ASC, `Year` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_club1`
    FOREIGN KEY (`ClubOneId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_club2`
    FOREIGN KEY (`ClubTwoId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_round1`
    FOREIGN KEY (`BeforeRound` , `Year`)
    REFERENCES `mydb`.`round` (`Number` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player_round` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player_round` (
  `Score` INT NOT NULL,
  `Ranked` INT NULL,
  `AddedPosition` ENUM('DEF', 'MID', 'RUC', 'FWD') NULL,
  `Tog` INT NULL,
  `RoundNumber` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `PlayerId` INT NOT NULL,
  PRIMARY KEY (`RoundNumber`, `Year`, `PlayerId`),
  INDEX `fk_player round_player1_idx` (`PlayerId` ASC) VISIBLE,
  CONSTRAINT `fk_player round_round1`
    FOREIGN KEY (`RoundNumber` , `Year`)
    REFERENCES `mydb`.`round` (`Number` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player round_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player_move` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player_move` (
  `TradeId` INT NOT NULL,
  `PlayerId` INT NOT NULL,
  `ClubIdFrom` INT NOT NULL,
  `ClubIdTo` INT NOT NULL,
  PRIMARY KEY (`TradeId`, `PlayerId`),
  INDEX `fk_player_move_transaction1_idx` (`TradeId` ASC) VISIBLE,
  INDEX `fk_player_move_player1_idx` (`PlayerId` ASC) VISIBLE,
  CONSTRAINT `fk_player_move_transaction1`
    FOREIGN KEY (`TradeId`)
    REFERENCES `mydb`.`trade` (`TradeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_move_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fa_interaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fa_interaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fa_interaction` (
  `WhenPerformed` DATETIME NOT NULL,
  `Type` ENUM('Drop', 'Add') NOT NULL,
  `RoundNumber` INT NOT NULL,
  `Year` YEAR NOT NULL,
  `ClubId` INT NOT NULL,
  `PlayerId` INT NOT NULL,
  PRIMARY KEY (`WhenPerformed`, `PlayerId`),
  INDEX `fk_fa_interaction_round1_idx` (`RoundNumber` ASC, `Year` ASC) VISIBLE,
  INDEX `fk_fa_interaction_club1_idx` (`ClubId` ASC) VISIBLE,
  INDEX `fk_fa_interaction_player1_idx` (`PlayerId` ASC) VISIBLE,
  CONSTRAINT `fk_fa_interaction_round1`
    FOREIGN KEY (`RoundNumber` , `Year`)
    REFERENCES `mydb`.`round` (`Number` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fa_interaction_club1`
    FOREIGN KEY (`ClubId`)
    REFERENCES `mydb`.`club` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fa_interaction_player1`
    FOREIGN KEY (`PlayerId`)
    REFERENCES `mydb`.`player` (`PlayerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
